tasks:
  - name: UseNode20
    command: |
      nvm install 20
      nvm use 20
      nvm alias default  20
  - name: Setup project
    before: corepack enable
    init: pnpm install
    command: pnpm build:wc
vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - rome.rome
    - ZixuanChen.vitest-explorer
    - vscode-icons-team.vscode-icons
